In [46]:
import pykeen
pykeen.env()

In [2]:
from pykeen.pipeline import pipeline
pipeline_result = pipeline(
    dataset='Nations',
    model='TransE',
)
pipeline_result.save_to_directory('nations_transe')

/home/david/Repos/FMI/SW-LinkPrediction/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
No random seed is specified. Setting to 665009975.
No cuda devices were available. The model runs on CPU
Training epochs on cpu:   0%|                                                                                                                                                                                                                                                     | 0/5 [00:00<?, ?epoch/s]
Training batches on cpu:   0%|                                                                                                                                                                                                                                                    | 0/7 [00:00<?, ?batch/s]
Training batches on cpu:  29%|███████████████████████████████████████████████████████████████████▍                                                                                                                                                                        | 2/7 [00:00<00:00, 17.71batch/s]
Training batches on cpu:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 6/7 [00:00<00:00, 29.65batch/s]
Training epochs on cpu:  20%|██████████████████████████████████████████▏                                                                                                                                                                        | 1/5 [00:00<00:02,  1.88epoch/s, loss=1.43, prev_loss=nan]
Training batches on cpu:   0%|                                                                                                                                                                                                                                                    | 0/7 [00:00<?, ?batch/s]
Training epochs on cpu:  40%|████████████████████████████████████████████████████████████████████████████████████                                                                                                                              | 2/5 [00:00<00:01,  2.34epoch/s, loss=1.31, prev_loss=1.43]
Training batches on cpu:   0%|                                                                                                                                                                                                                                                    | 0/7 [00:00<?, ?batch/s]
Training epochs on cpu:  60%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                    | 3/5 [00:01<00:00,  2.51epoch/s, loss=1.33, prev_loss=1.31]
Training batches on cpu:   0%|                                                                                                                                                                                                                                                    | 0/7 [00:00<?, ?batch/s]
Training epochs on cpu:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                          | 4/5 [00:01<00:00,  2.71epoch/s, loss=1.33, prev_loss=1.33]
Training batches on cpu:   0%|                                                                                                                                                                                                                                                    | 0/7 [00:00<?, ?batch/s]
Training epochs on cpu: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.64epoch/s, loss=1.28, prev_loss=1.33]
Evaluating on cpu:   0%|                                                                                                                                                                                                                                                    | 0.00/201 [00:00<?, ?triple/s]WARNING:torch_max_mem.api:Encountered tensors on device_types={'cpu'} while only ['cuda'] are considered safe for automatic memory utilization maximization. This may lead to undocumented crashes (but can be safe, too).
Evaluating on cpu: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:00<00:00, 2.05ktriple/s]
INFO:pykeen.evaluation.evaluator:Evaluation took 0.11s seconds
INFO:pykeen.triples.triples_factory:Stored TriplesFactory(num_entities=14, num_relations=55, create_inverse_triples=False, num_triples=1592, path="/home/david/Repos/FMI/SW-LinkPrediction/.venv/lib/python3.12/site-packages/pykeen/datasets/nations/train.txt") to file:///home/david/Repos/FMI/SW-LinkPrediction/nations_transe/training_triples
INFO:pykeen.pipeline.api:Saved to directory: /home/david/Repos/FMI/SW-LinkPrediction/nations_transe

In [3]:
pipeline_result.metric_results.to_df().to_csv("evaluationGood.csv")

In [42]:
pipeline_result.metric_results.get_metric("inverseharmonicmeanrank")

0.2769860625267029

In [44]:
pipeline_result.metric_results.get_metric("hits_at_1")

0.0

In [45]:
pipeline_result.metric_results.get_metric("hits_at_3")

0.39552238805970147

In [43]:
pipeline_result.metric_results.get_metric("hits_at_10")

0.9577114427860697

In [5]:
import torch
from pykeen.datasets import Nations

triples_factory = Nations().training

# Get tensor of entity identifiers
entity_ids = torch.as_tensor(triples_factory.entities_to_ids(["china", "egypt"]))

In [6]:
entity_ids

tensor([2, 4])

In [7]:
triples_factory

TriplesFactory(num_entities=14, num_relations=55, create_inverse_triples=False, num_triples=1592, path="/home/david/Repos/FMI/SW-LinkPrediction/.venv/lib/python3.12/site-packages/pykeen/datasets/nations/train.txt")

In [8]:
relation_ids = torch.as_tensor(triples_factory.relations_to_ids(["independence", "embassy"]))

In [9]:
relation_ids

tensor([19, 14])

In [53]:

from pykeen.predict import predict_all
pack = predict_all(model=pipeline_result.model, k=50)

WARNING:pykeen.predict:predict is an expensive operation, involving 10,780 score evaluations.

In [ ]:
# from pykeen.datasets import get_dataset
# from pykeen.predict import predict_triples
# dataset = get_dataset(dataset="nations")
# pack = predict_triples(model=pipeline_result.model, triples=dataset.validation)

In [54]:
predictionsDF = pack.process().df

predictionsDF

    head_id  relation_id  tail_id     score
0         6           11        6 -5.739488
1         4           11        4 -5.739488
2         0           11        0 -5.739488
3         9           11        9 -5.739488
4        10           11       10 -5.739488
5        12           11       12 -5.739488
6        13           11       13 -5.739489
7         1           11        1 -5.739489
8         3           11        3 -5.739489
9         2           11        2 -5.739489
10        7           11        7 -5.739489
11        5           11        5 -5.739489
12        8           11        8 -5.739489
13       11           11       11 -5.739489
14        1           40        1 -5.927323
15        7           40        7 -5.927323
16        9           40        9 -5.927323
17       11           40       11 -5.927323
18       13           40       13 -5.927323
19        0           40        0 -5.927323
20        8           40        8 -5.927323
21        2           40        2 -5.927323
22        3           40        3 -5.927323
23        4           40        4 -5.927323
24        5           40        5 -5.927323
25        6           40        6 -5.927323
26       12           40       12 -5.927323
27       10           40       10 -5.927323
28        8           22        8 -5.929996
29        3           22        3 -5.929996
30        9           22        9 -5.929996
31        4           22        4 -5.929996
32       13           22       13 -5.929996
33       12           22       12 -5.929996
34       11           22       11 -5.929996
35        7           22        7 -5.929996
36        2           22        2 -5.929996
37        0           22        0 -5.929996
38        1           22        1 -5.929996
39        5           22        5 -5.929996
40        6           22        6 -5.929996
41       10           22       10 -5.929996
42        6           12        6 -5.962485
43        5           12        5 -5.962485
44        1           12        1 -5.962485
45        2           12        2 -5.962485
46        8           12        8 -5.962485
47       11           12       11 -5.962485
48        7           12        7 -5.962485
49        0           12        0 -5.962485

In [16]:
predictionsDF.to_csv("first50Predictions.csv", index = None)

In [19]:
from pykeen.predict import predict_triples
from pykeen.datasets import get_dataset
dataset = get_dataset(dataset="nations")
pack = predict_triples(model=pipeline_result.model, triples=dataset.validation)

INFO:pykeen.datasets.utils:Loading cached preprocessed dataset from file:///home/david/.data/pykeen/datasets/nations/cache/47DEQpj8HBSa-_TImW-5JCeuQeRkm5NM
INFO:pykeen.triples.triples_factory:Loading from file:///home/david/.data/pykeen/datasets/nations/cache/47DEQpj8HBSa-_TImW-5JCeuQeRkm5NM/training
INFO:pykeen.triples.triples_factory:Loading from file:///home/david/.data/pykeen/datasets/nations/cache/47DEQpj8HBSa-_TImW-5JCeuQeRkm5NM/testing
INFO:pykeen.triples.triples_factory:Loading from file:///home/david/.data/pykeen/datasets/nations/cache/47DEQpj8HBSa-_TImW-5JCeuQeRkm5NM/validation
WARNING:torch_max_mem.api:Encountered tensors on device_types={'cpu'} while only ['cuda'] are considered safe for automatic memory utilization maximization. This may lead to undocumented crashes (but can be safe, too).

In [52]:
df = pack.process(factory=pipeline_result.training).df

In [50]:
df.nlargest(n=30, columns="score")

,head_id,head_label,relation_id,relation_label,tail_id,tail_label,score
85,6,indonesia,25,negativebehavior,13,ussr,-7.979125
22,1,burma,33,reldiplomacy,10,poland,-7.994029
159,11,uk,40,relstudents,12,usa,-8.277664
117,9,netherlands,20,intergovorgs,12,usa,-8.310967
152,11,uk,18,exports3,12,usa,-8.370900
145,11,uk,9,conferences,12,usa,-8.400039
131,10,poland,32,relbooktranslations,13,ussr,-8.429682
116,9,netherlands,20,intergovorgs,10,poland,-8.430938
188,13,ussr,28,ngoorgs3,12,usa,-8.446953
57,3,cuba,26,negativecomm,12,usa,-8.458603
35,2,china,26,negativecomm,12,usa,-8.500444
65,4,egypt,18,exports3,11,uk,-8.571322
174,12,usa,45,timesinceally,10,poland,-8.652911
119,9,netherlands,28,ngoorgs3,12,usa,-8.662274
180,13,ussr,14,embassy,6,indonesia,-8.727304
30,2,china,14,embassy,3,cuba,-8.730482
193,13,ussr,38,relintergovorgs,5,india,-8.759008
177,12,usa,49,treaties,10,poland,-8.780572
139,10,poland,48,tourism3,13,ussr,-8.788110
196,13,ussr,45,timesinceally,9,netherlands,-8.793416
36,2,china,26,negativecomm,13,ussr,-8.823659
16,1,burma,14,embassy,13,ussr,-8.827389
175,12,usa,47,tourism,4,egypt,-8.828839
15,1,burma,14,embassy,7,israel,-8.832802
17,1,burma,21,intergovorgs3,9,netherlands,-8.876416
77,5,india,23,militaryactions,2,china,-8.902822
62,3,cuba,49,treaties,2,china,-8.906569
166,12,usa,19,independence,10,poland,-8.923439
125,10,poland,14,embassy,7,israel,-8.924827
73,5,india,8,commonbloc2,4,egypt,-8.930785

In [ ]:
pipeline_result.training

In [23]:
pack_testing = predict_triples(model=pipeline_result.model, triples=dataset.testing)

WARNING:torch_max_mem.api:Encountered tensors on device_types={'cpu'} while only ['cuda'] are considered safe for automatic memory utilization maximization. This may lead to undocumented crashes (but can be safe, too).

In [26]:
df_testing = pack_testing.process(factory=pipeline_result.training).df

In [27]:
df_testing.nlargest(n=20, columns="score")

,head_id,head_label,relation_id,relation_label,tail_id,tail_label,score
138,9,netherlands,48,tourism3,13,ussr,-7.124514
192,13,ussr,4,booktranslations,12,usa,-7.809344
125,9,netherlands,6,commonbloc0,2,china,-7.842781
133,9,netherlands,27,ngo,5,india,-8.123978
173,12,usa,14,embassy,11,uk,-8.210761
196,13,ussr,33,reldiplomacy,12,usa,-8.233860
9,1,burma,18,exports3,5,india,-8.250392
0,0,brazil,7,commonbloc1,5,india,-8.341712
148,10,poland,33,reldiplomacy,12,usa,-8.381327
27,2,china,21,intergovorgs3,12,usa,-8.469832
140,10,poland,8,commonbloc2,13,ussr,-8.481221
152,10,poland,54,weightedunvote,9,netherlands,-8.481957
186,12,usa,51,unweightedunvote,7,israel,-8.487302
174,12,usa,19,independence,2,china,-8.525639
37,3,cuba,21,intergovorgs3,11,uk,-8.542912
92,6,indonesia,28,ngoorgs3,5,india,-8.564227
28,2,china,21,intergovorgs3,13,ussr,-8.593511
139,9,netherlands,49,treaties,12,usa,-8.637435
116,8,jordan,28,ngoorgs3,12,usa,-8.740534
145,10,poland,28,ngoorgs3,13,ussr,-8.773811

In [28]:
from pykeen.evaluation import LCWAEvaluationLoop
evaluation_loop = LCWAEvaluationLoop(
    model=pipeline_result.model,
    triples_factory=dataset.testing,
)

WARNING:pykeen.evaluation.evaluation_loop:Enabled filtered evaluation, but not additional filter triples are passed.

In [29]:
evaluation = evaluation_loop.evaluate()

evaluation: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13.0/13.0 [00:00<00:00, 244batch/s]

In [30]:
print(evaluation)

<pykeen.evaluation.rank_based_evaluator.RankBasedMetricResults object at 0x74b63c2b9640>

In [31]:
evaluation

In [47]:
evaluation.get_metric("inverseharmonicmeanrank")

0.1843836009502411